Check'n'refactor
starcraft66/SOEN341-Fall-2020-ProjectB pull request #26
Opened 2020-11-23 19:02 UTC by RhysRosenberg

2020-11-24 18:23 UTC, starcraft66 requested changes
Looking mostly good except for a missing docstring.

2020-11-24 18:23 UTC, starcraft66 commented on src/test/java/co/tdude/soen341/projectb/test/AssemblerTest.java
> +    static void SetupTestFile(/*@TempDir File tempDir*/) throws IOException {
This comment can be removed since we don't use the JUnit temp dir anymore

2020-11-24 18:23 UTC, starcraft66 commented on src/main/java/co/tdude/soen341/projectb/Lexer/Tokens/NumberToken.java
> +
We probably wanna have a short javadoc comment for the accessor

2020-11-24 22:26 UTC, karimrhoualem requested changes
@RhysRosenberg Please take a look at how the column position is incremented in Lexer and let me know if the change is required. Thanks

2020-11-24 22:26 UTC, karimrhoualem commented on src/main/java/co/tdude/soen341/projectb/Lexer/Lexer.java
> +            _curColPos++;
Shouldn't _curColPos be placed outside of this while loop? The column position should only be incremented when we're done scanning the identifier completely, not for each character that's scanned

2020-11-24 23:56 UTC, RhysRosenberg commented on src/main/java/co/tdude/soen341/projectb/Lexer/Lexer.java
> +            _curColPos++;
after chatting we agreed that curColPos should increment on every char received instead of every token

2020-11-25 00:01 UTC, karimrhoualem approved these changes

2020-11-25 00:03 UTC, RhysRosenberg reviewed
changes are... good? is this what i'm meant to do

2020-11-25 03:40 UTC, merged